### ISSUE TITLE
Build of dependencies failing consistently on bytecode target

### ISSUE THREAD

**Issue by shym** [ocaml-multicore/multicoretests#258]
Since Wednesday the 7th, between 16:00 and 17:00 UTC, all builds on bytecode started to fail.
I traced it to ocaml-multicore/lockfree#34 which pulls in (recursively) many new dependencies, some of which cannot build on bytecode (`containers`).

**Comment by jmid** [comment]
Could you file an issue on `lockfree` (or `containers`) with a summary of steps to reproduce?
That way we help keep the good ecosystem karma :smile:

**Comment by shym** [comment]
That was indeed in the pipeline :smile:
Now opened in https://github.com/c-cube/ocaml-containers/pull/421
