### ISSUE TITLE
[ocaml5-issue] BUS error on the Weak Hashset tests on macOS 5.0.0

### ISSUE THREAD

**Issue by jmid** [ocaml-multicore/multicoretests#283]
Ouch, `STM` tests trigger a BUS error on the `Weak` `Hashset` tests on macOS 5.0.0
https://github.com/ocaml-multicore/multicoretests/actions/runs/3913104092/jobs/6688588995
```
random seed: 470692489
generated error fail pass / total     time test name

[ ]    0    0    0    0 / 1000     0.0s STM Weak test sequential
[ ]    0    0    0    0 / 1000     0.0s STM Weak test sequential (generating)
[✓] 1000    0    0 1000 / 1000     0.3s STM Weak test sequential

[ ]    0    0    0    0 / 1000     0.0s STM Weak test parallel
[ ]   53    0    0   53 / 1000    63.2s STM Weak test parallel
[ ]  141    0    0  141 / 1000   124.4s STM Weak test parallel
[ ]  196    0    0  196 / 1000   186.8s STM Weak test parallel
[ ]  271    0    0  271 / 1000   252.0s STM Weak test parallel
[ ]  375    0    0  375 / 1000   315.7s STM Weak test parallel
[✓]  383    0    1  382 / 1000   336.4s STM Weak test parallel

[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test sequential
[✓] 1000    0    0 1000 / 1000     0.4s STM Weak HashSet test sequential

[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test parallel
[ ]   51    0    0   51 / 1000    38.9s STM Weak HashSet test parallel (shrinking:   19.0052)
[ ]   51    0    0   51 / 1000    98.9s STM Weak HashSet test parallel (shrinking:   23.0034)
[ ]   51    0    0   51 / 1000   159.0s STM Weak HashSet test parallel (shrinking:   25.0124)
[ ]   51    0    0   51 / 1000   219.1s STM Weak HashSet test parallel (shrinking:   27.0081)
[ ]   51    0    0   51 / 1000   279.1s STM Weak HashSet test parallel (shrinking:   29.0113)
[ ]   51    0    0   51 / 1000   339.2s STM Weak HashSet test parallel (shrinking:   32.0109)
[ ]   51    0    0   51 / 1000   399.3s STM Weak HashSet test parallel (shrinking:   35.0062)
[ ]   51    0    0   51 / 1000   459.3s STM Weak HashSet test parallel (shrinking:   38.0082)
[ ]   51    0    0   51 / 1000   519.5s STM Weak HashSet test parallel (shrinking:   41.0050)
File "src/weak/dune", line 4, characters 7-16:
4 |  (name stm_tests)
           ^^^^^^^^^
(cd _build/default/src/weak && ./stm_tests.exe --verbose)
Command got signal BUS.
[ ]   51    0    0   51 / 1000   579.6s STM Weak HashSet test parallel (shrinking:   44.0023)
```

_Originally posted by @jmid in https://github.com/ocaml-multicore/multicoretests/issues/214#issuecomment-1382420916_

**Comment by jmid** [comment]
By repeating this test I was able to trigger it on Linux 5.0.0 - 2 times out of 20:
https://github.com/ocaml-multicore/multicoretests/actions/runs/3947752112/jobs/6756942540
```
Starting 4-th run

random seed: 345857112
generated error fail pass / total     time test name

[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test sequential
[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test sequential (generating)
[✓] 1000    0    0 1000 / 1000     0.5s STM Weak HashSet test sequential

/home/runner/work/_temp/b341ea64-be49-4681-bc18-f45cf3fb5fc1.sh: line 2: 689245 Segmentation fault      (core dumped) opam exec -- dune exec "$ONLY_TEST" -- -v
[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test parallel
```

```
Starting 17-th run

random seed: 185727102
generated error fail pass / total     time test name

[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test sequential
[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test sequential (generating)
[✓] 1000    0    0 1000 / 1000     0.5s STM Weak HashSet test sequential

[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test parallel
/home/runner/work/_temp/b341ea64-be49-4681-bc18-f45cf3fb5fc1.sh: line 2: 2265391 Segmentation fault      (core dumped) opam exec -- dune exec "$ONLY_TEST" -- -v
[ ]  134    0    0  134 / 1000    60.9s STM Weak HashSet test parallel (shrinking:    2.0003)
```

**Comment by jmid** [comment]
Here's another variant also on macOS with 5.0.0:
https://github.com/ocaml-multicore/multicoretests/actions/runs/3950979181/jobs/6764237257
```
Starting 4-th run

random seed: 34289257
generated error fail pass / total     time test name

[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test sequential
[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test sequential (generating)
[✓] 1000    0    0 1000 / 1000     0.4s STM Weak HashSet test sequential

[ ]    0    0    0    0 / 1500     0.0s STM Weak HashSet test parallel
Fatal error: allocation failure during minor GC
/Users/runner/work/_temp/dc6e4576-d0a5-4e46-b8e5-50401ba047bd.sh: line 2: 68483 Abort trap: 6           opam exec -- dune exec "$ONLY_TEST" -- -v
```

I've only seen it so far on 5.0.0 - not on trunk. 
Either this is a coincidence or otherwise something merged into trunk fixed it or prevents it from occurring as often? :thinking:

**Comment by dra27** [comment]
If it’s crashing relatively frequently, is it with a bisect on trunk to get a hint as to what might have fixed it (or might therefore be masking it)?

**Comment by shym** [comment]
I’m trying the tests on 5.0.1: https://github.com/shym/multicoretests/actions?query=branch%3Atorture-weak-segv++

**Comment by jmid** [comment]
I've tried recreating this locally on my Linux box with 5.0.0.
Running `for run in {1..10}; do _build/default/src/weak/stm_tests_hashset.exe -v -s 345857112; done` has reproduced at least 1 crash in 10 iterations - when running this loop for the past 3 times.

Looking at the source code of the Hashsets in `weak.ml` I see lots of race possibilities, e.g., two internal arrays assumed to have equal length, but no ocaml-code using`unsafe` AFAICS. There's also some usage of `blit` - which comes with some parallelism caveats IIRC :thinking: 

Finally I was reminding myself of https://github.com/ocaml/ocaml/pull/11743 - which makes changes to the runtime underlying `Weak arrays` - and hence may explain why we've only seen this on `5.0.0` and not on `trunk`.

**Comment by jmid** [comment]
A quick update:
- I can reproduce this problem locally on a reinstall of the opam `5.0.1+trunk` package, which should match the `5.0` branch
- I can also reproduce it locally on commit `7942816c0 - Merge pull request #11761 from Sudha247/code-of-conduct` from just before ocaml/ocaml#11743 was merged
- I cannot trigger it locally on commit `6978b365c - Merge pull request #11743 from kayceesrk/ephemeron_improvements`
- I cannot trigger it locally on the latest `trunk`

Unfortunately this doesn't prove anything. 
@kayceesrk pointed out that ocaml/ocaml#11743 changes the timing of collecting `Weak array`s. 
So either it happens to fix a GC problem in the process - or it just shadows an underlying issue and makes it harder to reproduce :shrug:

**Comment by jmid** [comment]
Closing as this is now reported and tracked [in an upstream issue](https://github.com/ocaml/ocaml/issues/11934).
