### ISSUE TITLE
Switch CI to use trunk branch from ppxlib?

### ISSUE THREAD

**Issue by jmid** [ocaml-multicore/multicoretests#317]
Sonja announced a centrally maintained `trunk` supporting branch of ppxlib:
  https://discuss.ocaml.org/t/ann-ppxlib-trunk-support-non-continuous/11758

It may make sense to switch our CI workflows to use it, as it relieves us from maintaining a branch by ourselves.

**Comment by shym** [comment]
I propose to do this [changes] (https://github.com/shym/custom-opam-repository/compare/master...ppxlib-trunk) on my opam repo, whenever the latest AST change is dealt with there.
Or do you think it would better be in the opam “repo” embedded in multicoretests?
